name: Check for new FXserver versions
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-versions:
    name: Check for new versions
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.parse-json.outputs.latest }}
      latest_url: ${{ steps.parse-json.outputs.latest_url }}
      recommended: ${{ steps.parse-json.outputs.recommended }}
      recommended_url: ${{ steps.parse-json.outputs.recommended_url }}
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
      has_recommended_changes: ${{ steps.check-recommended-changes.outputs.has_recommended_changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          
      - name: Fetch version data
        id: fetch-data
        run: |
          curl -s https://changelogs-live.fivem.net/api/changelog/versions/linux/server > versions.json
          cat versions.json
      
      - name: Parse JSON data
        id: parse-json
        run: |
          latest=$(jq -r '.latest' versions.json)
          latest_url=$(jq -r '.latest_download' versions.json)
          recommended=$(jq -r '.recommended' versions.json)
          recommended_url=$(jq -r '.recommended_download' versions.json)
          
          echo "latest=$latest" >> $GITHUB_OUTPUT
          echo "latest_url=$latest_url" >> $GITHUB_OUTPUT
          echo "recommended=$recommended" >> $GITHUB_OUTPUT
          echo "recommended_url=$recommended_url" >> $GITHUB_OUTPUT
      
      - name: Check for latest changes
        id: check-changes
        run: |
          latest="${{ steps.parse-json.outputs.latest }}"

          if git rev-parse "$latest" >/dev/null 2>&1; then
            echo "No new latest versions detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "New latest version detected: $latest"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for recommended changes
        id: check-recommended-changes
        run: |
          recommended="${{ steps.parse-json.outputs.recommended }}"

          if git fetch origin recommended && git tag --list --points-at origin/recommended | grep -q "^$recommended$"; then
            echo "Tag for recommended version $recommended already exists"
            echo "has_recommended_changes=false" >> $GITHUB_OUTPUT
          else
            echo "New recommended version detected: $recommended"
            echo "has_recommended_changes=true" >> $GITHUB_OUTPUT
          fi

  new-latest:
    name: Create PR for latest
    runs-on: ubuntu-latest
    needs: check-versions
    if: needs.check-versions.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      
      - name: Update Dockerfile
        run: perl -i -pe 's,(?<=curl ).*(?= \|),${{ needs.check-versions.outputs.latest_url }},' Dockerfile
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Commit Dockerfile
        run: "git commit -m '[Auto] New FXServer version: ${{ needs.check-versions.outputs.latest }}' -a"
      
      - name: Create tag
        run: git tag ${{ needs.check-versions.outputs.latest }}
      
      - name: Push new tag
        run: |
          git push
          git push origin ${{ needs.check-versions.outputs.latest }}
  
  new-recommended:
    name: Create PR for recommended
    runs-on: ubuntu-latest
    needs: ["check-versions"]
    if: needs.check-versions.outputs.has_recommended_changes == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "recommended"
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Update Dockerfile
        run: perl -i -pe 's,(?<=curl ).*(?= \|),${{ needs.check-versions.outputs.recommended_url }},' Dockerfile

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit Dockerfile
        run: "git commit -m '[Auto] New FXServer version: ${{ needs.check-versions.outputs.recommended }}' -a"

      - name: Create tag
        run: git tag ${{ needs.check-versions.outputs.recommended }}

      - name: Push new tag  
        run: |
          git push
          git push origin ${{ needs.check-versions.outputs.recommended }}

